/**
 * Deterministic learning-path generator.
 *
 * This is the piece the README promises ("deterministic, capacity-aware
 * learning paths ... generated by Gemma 4 backend tools") but that wasn't
 * actually implemented — chatService.js was returning the same 3 generic
 * bullets for every track and level. This file replaces that placeholder
 * with real, distinct curricula per track x level.
 *
 * Kept deterministic on purpose: Gemma/the agent decides WHICH track and
 * level apply to this user (via inferTrackFromMessage / inferLevelFromMessage),
 * but the actual path CONTENT is a fixed, reviewable lookup table rather than
 * something the model freely generates each time. That means the same
 * track+level always produces the same path (predictable, testable, no
 * hallucinated steps), while the conversation *around* it is still LLM-driven.
 */

const TRACKS = {
  Frontend: {
    beginner: [
      "HTML, CSS & responsive layout basics",
      "JavaScript fundamentals (ES6+)",
      "Intro to React: components & props",
      "State management with hooks",
      "Build & deploy a small React app",
    ],
    intermediate: [
      "Advanced React patterns (context, custom hooks)",
      "TypeScript for React",
      "Testing with React Testing Library",
      "Performance & bundle optimization",
      "Contribute to an open-source frontend issue",
    ],
  },
  Backend: {
    beginner: [
      "Node.js & JavaScript runtime basics",
      "Building REST APIs with Express",
      "Working with databases (SQL basics)",
      "Authentication fundamentals",
      "Deploy a simple API",
    ],
    intermediate: [
      "API design & versioning",
      "Database performance & indexing",
      "Caching & rate limiting",
      "Testing & CI for backend services",
      "Contribute to an open-source backend issue",
    ],
  },
  "Project Management": {
    beginner: [
      "Agile & Scrum fundamentals",
      "Writing clear user stories & backlogs",
      "Running a standup & sprint planning",
      "Basic roadmapping & prioritization",
      "Run a full sprint end-to-end with a mentor reviewing",
    ],
    intermediate: [
      "Stakeholder management & communication",
      "Risk management & mitigation planning",
      "Metrics: velocity, burndown, cycle time",
      "Cross-team coordination on larger projects",
      "Lead a real sprint retro and present outcomes",
    ],
  },
};

const DEFAULT_TRACK = "Frontend";
const DEFAULT_LEVEL = "beginner";

/**
 * @param {{track?: string, level?: string}} params
 * @returns {{track: string, level: string, steps: string[], estimatedWeeks: number}}
 */
function generateLearningPath({ track, level } = {}) {
  const normalizedTrack = TRACKS[track] ? track : DEFAULT_TRACK;
  const normalizedLevel = level === "intermediate" ? "intermediate" : DEFAULT_LEVEL;

  const steps = TRACKS[normalizedTrack][normalizedLevel];

  return {
    track: normalizedTrack,
    level: normalizedLevel,
    steps,
    estimatedWeeks: steps.length,
  };
}

function listAvailableTracks() {
  return Object.keys(TRACKS);
}

module.exports = { generateLearningPath, listAvailableTracks };
